// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUrlPKeXYSz8R-Qt4YJfS302bQKCNyo9k',
    appId: '1:1017752508261:web:003434bd89db2839eaf38c',
    messagingSenderId: '1017752508261',
    projectId: 'chalostaad',
    authDomain: 'chalostaad.firebaseapp.com',
    storageBucket: 'chalostaad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDar8vgzBjfDex2G3ItLI0CZjWRAW58-Qk',
    appId: '1:1017752508261:android:bf69c7bd9a6eef08eaf38c',
    messagingSenderId: '1017752508261',
    projectId: 'chalostaad',
    storageBucket: 'chalostaad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqnsQU8MWlueNXJiB0yyyo1Rdj2jJE5RY',
    appId: '1:1017752508261:ios:a3987fec51423568eaf38c',
    messagingSenderId: '1017752508261',
    projectId: 'chalostaad',
    storageBucket: 'chalostaad.firebasestorage.app',
    iosBundleId: 'com.example.chalOstaad',
  );
}
